#!/bin/bash

# Define the base folder
baseFolder="/public"

# Get the client name from arguments
clientName=$1

# Define client folder
clientFolder="${baseFolder}/${clientName}"

# Create the client folder
mkdir -p "$clientFolder"

# Check if the client already exists
CLIENTEXISTS=$(tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep -c -E "/CN=$clientName\$")
if [[ $CLIENTEXISTS == '1' ]]; then
    echo "The specified client CN was already found in easy-rsa, please choose another name."
    exit
else
    cd /etc/openvpn/easy-rsa/ || exit
    ./easyrsa --batch build-client-full "$clientName" nopass
    echo "Client $clientName added."
fi

# Generate the custom client.ovpn
cp /etc/openvpn/client-template.txt "$clientFolder/$clientName.ovpn"
{
    echo "<ca>"
    cat "/etc/openvpn/easy-rsa/pki/ca.crt"
    echo "</ca>"

    echo "<cert>"
    awk '/BEGIN/,/END CERTIFICATE/' "/etc/openvpn/easy-rsa/pki/issued/$clientName.crt"
    echo "</cert>"

    echo "<key>"
    cat "/etc/openvpn/easy-rsa/pki/private/$clientName.key"
    echo "</key>"

    if grep -qs "^tls-crypt" /etc/openvpn/server.conf; then
        echo "<tls-crypt>"
        cat /etc/openvpn/tls-crypt.key
        echo "</tls-crypt>"
    elif grep -qs "^tls-auth" /etc/openvpn/server.conf; then
        echo "key-direction 1"
        echo "<tls-auth>"
        cat /etc/openvpn/tls-auth.key
        echo "</tls-auth>"
    fi
} >>"$clientFolder/$clientName.ovpn"

echo "Success"
exit 0
